name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      php-version:
        - "8.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Run Pint
        run: vendor/bin/pint --test
      - name: Run PHPCS
        run: vendor/bin/phpcs ./
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
      - name: Run PHPUnit
        run: vendor/bin/phpunit tests